services:
  postgres:
    image: postgres:17
    container_name: sre-job-market-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: jobmarket
      POSTGRES_USER: jobmarket
      POSTGRES_PASSWORD: jobmarket

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobmarket"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: